### ISSUE TITLE
Drawing functions should take signed positions

### ISSUE THREAD

**Issue by Kapouett** [Enet4/dos-like-rs#4]
Drawing functions like `line` or `draw_poly` take `u16` coordinates, breaking shapes that are partially off-screen.
This behavior is not present in `dos-like` as it uses signed integer coordinates.

**Comment by Enet4** [comment]
Interesting! Although screen coordinates are always within the range `(0,0) - (W-1, H-1)`, the library does admit some of these to be outside the screen boundaries for legitimate use cases. I will rework the video module to fix this.
